### ISSUE TITLE
Support for node 0.12

### ISSUE THREAD

**Issue by martinsson** [wix/protractor-browser-logs#3]
I can't use the version 1.0.10 for the foreseable future as we have our whole infrastructure on 0.12. There's no old version available.

I'm submitting a patch, if it could be integrated in a off-numbered version it'd be great, until we move on to node 4/5.

**Comment by mastertheblaster** [comment]
Sorry for the issue, we have rolled back the change. Will fix in a near future most probably using the transpiler. So we could use all es6 goodies and still be compatible. The new version `1.0.11` has been released.

**Comment by martinsson** [comment]
This does not solve the issue for me on node 0.12. The files in dist still have arrow functions, so maybe it is compatible with node 4 but not before. Maybe I can try to change the babel options

  Message:
    Failed: undefined is not a function
  Stack:
    TypeError: undefined is not a function
        at /source/index.js:52:21
        at Array.filter (native)
        at removeMatchingMessages (/source/index.js:51:19)
        at /source/index.js:97:11
        at Array.forEach (native)

**Comment by martinsson** [comment]
Ah I suppose it is the lack of Array.prototype.find

**Comment by mastertheblaster** [comment]
Please give it a try now. Version `1.0.13` has been released. No babel polyfills are required.

**Comment by mastertheblaster** [comment]
I have tested with node `v0.12.13` and it worked for me.

**Comment by martinsson** [comment]
Yes that did it.

Thanks!
