### ISSUE TITLE
Use protractor-console with protractor-browser-logs

### ISSUE THREAD

**Issue by martinsson** [wix/protractor-browser-logs#6]
It seems like this thing eats up my console.log/console.warn etc

I would have preferred seeing all those logs as I do using the protractor-console plugin. Currently I have to comment out protractor-browser-logs to be able to debug using console.log

From what I see browser.manage().logs().get('browser') is "eating" up the logs so when protractor-browser-logs fires before protractor-console then there's nothing to log anymore.

**Comment by martinsson** [comment]
Indeed, the documentation for logs().get() from webdriver.js in selenium-webdriver

```

* Fetches available log entries for the given type.
 *
 * Note that log buffers are reset after each call, meaning that available
 * log entries correspond to those entries not yet returned for a given log
 * type. In practice, this means that this call will return the available log
 * entries since the last call, or from the start of the session.
 

```

I don't know if there is anything reasonable to do here

**Comment by mastertheblaster** [comment]
@martinsson Actually there is. I was thinking about extending the API. What do you say ?

```js
var browserLogs = require('protractor-browser-logs');

// 1. First example, using just a boolean parameter
logs = browserLogs(browser, {
   outputLog: true
});

// 2. Second example, using pluggable functions ran at verify() phase
logs = browserLogs(browser, {
   assertations: [function (logs) {
       console.log(logs);
   }]
});
```

**Comment by martinsson** [comment]
Nice idea.

Option 1 is good, easy and clear.
Option 2 is a bit surprising, however I like the flexibility. Maybe you can
add a new abstraction like reporters? ie

logs = browserLogs(browser, {

   assertions: [function (logs) {
       expect(...)
   },

reporters: [function (logs) { console.log(logs); }] });

**Comment by mastertheblaster** [comment]
@martinsson Done. 

Latest version `1.0.50` should do the trick:
https://github.com/wix/protractor-browser-logs#custom-reporters
